### ISSUE TITLE
bug: cannot create NFT

### ISSUE THREAD

**Issue by 7flash** [kodadot/grants#38]
When uploading data to IPFS, its showing following error:

```
TypeError: Cannot destructure property 'alreadyMinted' of 'r' as it is undefined.
    at le (useTransaction.777b68e0.js:1:11605)
    at useTransaction.777b68e0.js:1:12275
    at Array.flatMap (<anonymous>)
    at xe (useTransaction.777b68e0.js:1:12255)
    at qt (useTransaction.777b68e0.js:3:204)
    at jt (useTransaction.777b68e0.js:3:334)
    at useTransaction.777b68e0.js:1:12045
    at zt (useTransaction.777b68e0.js:3:821)
    at Object.MINTNFT (useTransaction.777b68e0.js:3:4590)
    at transaction (useTransaction.777b68e0.js:3:4718)
```

**Comment by yangwao** [comment]
Hello, this is not the right repository to post this; 
Please open the issue in nft-gallery
- https://github.com/kodadot/nft-gallery/issues/new/choose
Thanks
